/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.moduloActividades;

import DTOs.ActividadDTO;
import control.CoordinadorAplicacion;
import control.CoordinadorNegocio;
import exception.NegocioException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Formulario para el módulo de actividades. 
 * 
 * @author Alejandra García 252444
 */
public class ModuloActividadesForm extends javax.swing.JFrame {
    
    private List<ActividadDTO> listaActividades;
    private int actividadSeleccionadaIndex = -1;

    /**
     * Creates new form ModuloActividadesForm
     */
    public ModuloActividadesForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Módulo Actividades");
        inicializarTabla();
        cargarActividades();

        // Desactivar botones que requieren selección
        btnVerActividad.setEnabled(false);
        btnEditarActividad.setEnabled(false);
        btnGestionarParticipantes.setEnabled(false);

        // Agregar listener para selección de tabla
        tblActividades.getSelectionModel().addListSelectionListener(e -> {
            actividadSeleccionadaIndex = tblActividades.getSelectedRow();
            boolean filaSeleccionada = actividadSeleccionadaIndex != -1;
            btnVerActividad.setEnabled(filaSeleccionada);
            btnEditarActividad.setEnabled(filaSeleccionada);
            btnGestionarParticipantes.setEnabled(filaSeleccionada);
        });
    }
    
    private void inicializarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Tipo", "Fecha Hora", "Capacidad", "Duración", "Evento", "Lugar", "Finalizado"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblActividades.setModel(modelo);
    }

    private void cargarActividades() {
        try {
            listaActividades = CoordinadorNegocio.getInstancia().consultarTodasActividades();
            actualizarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar actividades: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            listaActividades = new ArrayList<>();
        }
    }

    private void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
        modelo.setRowCount(0);

        for (ActividadDTO actividad : listaActividades) {
            modelo.addRow(new Object[]{
                actividad.getNombre(),
                actividad.getTipo(),
                actividad.getFechaHoraInicio().toString(),
                actividad.getCapacidad(),
                actividad.getDuracion() + " min",
                actividad.getNombreEvento(),
                actividad.getNombreLugar(),
                actividad.getFinalizado() ? "Sí" : "No"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        btnVerActividad = new javax.swing.JButton();
        btnEditarActividad = new javax.swing.JButton();
        btnNuevaActividad = new javax.swing.JButton();
        btnGestionarParticipantes = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Módulo Actividades");

        tblActividades.setBackground(new java.awt.Color(255, 255, 255));
        tblActividades.setForeground(new java.awt.Color(0, 0, 0));
        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Fecha Hora", "Capacidad", "Duración", "Evento", "Lugar", "Responsable"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActividades.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblActividades);

        btnVerActividad.setBackground(new java.awt.Color(0, 0, 0));
        btnVerActividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnVerActividad.setText("Ver Actividad");
        btnVerActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActividadActionPerformed(evt);
            }
        });

        btnEditarActividad.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarActividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarActividad.setText("Marcar como Finalizada");
        btnEditarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActividadActionPerformed(evt);
            }
        });

        btnNuevaActividad.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevaActividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNuevaActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaActividad.setText("Nueva Actividad");
        btnNuevaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActividadActionPerformed(evt);
            }
        });

        btnGestionarParticipantes.setBackground(new java.awt.Color(0, 0, 0));
        btnGestionarParticipantes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGestionarParticipantes.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarParticipantes.setText("Gestionar Participantes");
        btnGestionarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarParticipantesActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVerActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGestionarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(btnNuevaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGestionarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActividadActionPerformed
        if (actividadSeleccionadaIndex != -1) {
            VerActividadForm.actividadSeleccionada = listaActividades.get(actividadSeleccionadaIndex);
            CoordinadorAplicacion.getInstancia().mostrarVerActividad();
            this.dispose();
        }
    }//GEN-LAST:event_btnVerActividadActionPerformed

    private void btnEditarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActividadActionPerformed
        if (actividadSeleccionadaIndex != -1) {
            ActividadDTO actividad = listaActividades.get(actividadSeleccionadaIndex);

            if (actividad.getFinalizado()) {
                JOptionPane.showMessageDialog(this,
                        "La actividad ya está marcada como finalizada.",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de marcar esta actividad como finalizada?",
                    "Confirmar finalización", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    CoordinadorNegocio.getInstancia().finalizarActividad(actividad);
                    JOptionPane.showMessageDialog(this,
                            "Actividad marcada como finalizada correctamente.",
                            "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    cargarActividades(); // Recargar la tabla
                } catch (NegocioException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Error al finalizar actividad: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnEditarActividadActionPerformed

    private void btnNuevaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActividadActionPerformed
        CoordinadorAplicacion.getInstancia().mostrarNuevaActividad();
        this.dispose();
    }//GEN-LAST:event_btnNuevaActividadActionPerformed

    private void btnGestionarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarParticipantesActionPerformed
        if (actividadSeleccionadaIndex != -1) {
            ParticipantesActividadForm.actividadSeleccionada = listaActividades.get(actividadSeleccionadaIndex);
            CoordinadorAplicacion.getInstancia().mostrarParticipantesActividad();
            this.dispose();
        }
    }//GEN-LAST:event_btnGestionarParticipantesActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        CoordinadorAplicacion.getInstancia().mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarActividad;
    private javax.swing.JButton btnGestionarParticipantes;
    private javax.swing.JButton btnNuevaActividad;
    private javax.swing.JButton btnVerActividad;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblActividades;
    // End of variables declaration//GEN-END:variables
}
