/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.moduloActividades;

/**
 *
 * @author alega
 */
public class NuevaActividadForm extends javax.swing.JFrame {

    /**
     * Creates new form NuevaActividadForm
     */
    public NuevaActividadForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEvento = new javax.swing.JLabel();
        campoEvento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEventos = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblNombreActividad = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        campoNombreActividad = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        campoDuracion = new javax.swing.JTextField();
        dateTimePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        lblLugar = new javax.swing.JLabel();
        campoCapacidad = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        campoLugar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaLugares = new javax.swing.JList<>();
        lblOrganizador = new javax.swing.JLabel();
        campoOrganizador = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaOrganizadores = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));

        lblEvento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEvento.setForeground(new java.awt.Color(0, 0, 0));
        lblEvento.setText("Evento:");

        campoEvento.setBackground(new java.awt.Color(255, 255, 255));
        campoEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoEvento.setForeground(new java.awt.Color(0, 0, 0));

        listaEventos.setBackground(new java.awt.Color(255, 255, 255));
        listaEventos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaEventos.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(listaEventos);

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nueva Actividad");

        lblNombreActividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreActividad.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreActividad.setText("Nombre de la actividad:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo:");

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(0, 0, 0));
        lblDuracion.setText("Duración:");

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaHora.setText("Fecha y hora:");

        campoNombreActividad.setBackground(new java.awt.Color(255, 255, 255));
        campoNombreActividad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNombreActividad.setForeground(new java.awt.Color(0, 0, 0));

        campoTipo.setBackground(new java.awt.Color(255, 255, 255));
        campoTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTipo.setForeground(new java.awt.Color(0, 0, 0));

        campoDuracion.setBackground(new java.awt.Color(255, 255, 255));
        campoDuracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDuracion.setForeground(new java.awt.Color(0, 0, 0));

        lblLugar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLugar.setForeground(new java.awt.Color(0, 0, 0));
        lblLugar.setText("Seleccionar lugar:");

        campoCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        campoCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoCapacidad.setForeground(new java.awt.Color(0, 0, 0));

        lblCapacidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCapacidad.setText("Capacidad:");

        campoLugar.setBackground(new java.awt.Color(255, 255, 255));
        campoLugar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoLugar.setForeground(new java.awt.Color(0, 0, 0));

        listaLugares.setBackground(new java.awt.Color(255, 255, 255));
        listaLugares.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaLugares.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(listaLugares);

        lblOrganizador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrganizador.setForeground(new java.awt.Color(0, 0, 0));
        lblOrganizador.setText("Seleccionar organizador:");

        campoOrganizador.setBackground(new java.awt.Color(255, 255, 255));
        campoOrganizador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoOrganizador.setForeground(new java.awt.Color(0, 0, 0));
        campoOrganizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOrganizadorActionPerformed(evt);
            }
        });

        listaOrganizadores.setBackground(new java.awt.Color(255, 255, 255));
        listaOrganizadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaOrganizadores.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(listaOrganizadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(556, 556, 556))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(67, 67, 67)
                                                .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(campoNombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(35, 35, 35)
                                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(288, 288, 288)
                                        .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento)
                    .addComponent(campoEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActividad)
                    .addComponent(campoNombreActividad))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(campoTipo)
                    .addComponent(lblDuracion)
                    .addComponent(campoDuracion)
                    .addComponent(lblFechaHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLugar)
                    .addComponent(lblCapacidad)
                    .addComponent(campoCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(campoLugar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblOrganizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoOrganizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void campoOrganizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOrganizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOrganizadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaActividadForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoCapacidad;
    private javax.swing.JTextField campoDuracion;
    private javax.swing.JTextField campoEvento;
    private javax.swing.JTextField campoLugar;
    private javax.swing.JTextField campoNombreActividad;
    private javax.swing.JTextField campoOrganizador;
    private javax.swing.JTextField campoTipo;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblNombreActividad;
    private javax.swing.JLabel lblOrganizador;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listaEventos;
    private javax.swing.JList<String> listaLugares;
    private javax.swing.JList<String> listaOrganizadores;
    // End of variables declaration//GEN-END:variables
}
