/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.moduloActividades;

import DTOs.ActividadDTO;
import DTOs.ActividadDetalleDTO;
import control.CoordinadorAplicacion;
import control.CoordinadorNegocio;
import exception.NegocioException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Formulario para ver una actividad del módulo de actividades.
 *
 * @author Alejandra García 252444
 */
public class VerActividadForm extends javax.swing.JFrame {
    
    public static ActividadDTO actividadSeleccionada;
    private ActividadDetalleDTO actividadDetalle;

    /**
     * Creates new form VerActividad
     */
    public VerActividadForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ver Actividad");

        if (actividadSeleccionada != null) {
            cargarDatosActividad();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Error: No se especificó una actividad para visualizar",
                    "Error", JOptionPane.ERROR_MESSAGE);
            volverAModuloActividades();
        }
    }
    
    private void cargarDatosActividad() {
        try {
            // Obtener detalles de la actividad usando los datos de la actividad seleccionada
            int indice = buscarIndiceActividad();

            if (indice != -1) {
                actividadDetalle = CoordinadorNegocio.getInstancia().consultarActividadDetalle(indice);
            } else {
                // Usar los datos básicos si no se puede obtener el detalle
                actividadDetalle = null;
            }

            // Cargar datos en los campos
            campoEvento.setText(actividadSeleccionada.getNombreEvento());
            campoNombre.setText(actividadSeleccionada.getNombre());
            campoTipo.setText(actividadSeleccionada.getTipo());
            campoDuracion.setText(actividadSeleccionada.getDuracion() + " minutos");

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            campoFechaHora.setText(actividadSeleccionada.getFechaHoraInicio().format(formatter));

            campoCapacidad.setText(actividadSeleccionada.getCapacidad().toString());
            campoLugar.setText(actividadSeleccionada.getNombreLugar());

            // Verificar si la actividad está finalizada para habilitar/deshabilitar botón
            btnMarcarFinalizada.setEnabled(!actividadSeleccionada.getFinalizado());
            if (actividadSeleccionada.getFinalizado()) {
                btnMarcarFinalizada.setText("Actividad Finalizada");
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar datos de la actividad: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int buscarIndiceActividad() throws NegocioException {
        List<ActividadDTO> actividades = CoordinadorNegocio.getInstancia().consultarTodasActividades();
        for (int i = 0; i < actividades.size(); i++) {
            ActividadDTO act = actividades.get(i);
            if (act.getNombre().equals(actividadSeleccionada.getNombre())
                    && act.getFechaHoraInicio().equals(actividadSeleccionada.getFechaHoraInicio())) {
                return i;
            }
        }
        return -1;
    }

    private void volverAModuloActividades() {
        CoordinadorAplicacion.getInstancia().mostrarModuloActividades();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEvento = new javax.swing.JLabel();
        lblNombreActividad = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        lblCapacidad = new javax.swing.JLabel();
        lblLugar = new javax.swing.JLabel();
        lblOrganizador = new javax.swing.JLabel();
        btnGestionarParticipantes = new javax.swing.JButton();
        campoEvento = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        campoDuracion = new javax.swing.JTextField();
        campoFechaHora = new javax.swing.JTextField();
        campoCapacidad = new javax.swing.JTextField();
        campoLugar = new javax.swing.JTextField();
        campoOrganizador = new javax.swing.JTextField();
        btnMarcarFinalizada = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ver Actividad");

        lblEvento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEvento.setForeground(new java.awt.Color(0, 0, 0));
        lblEvento.setText("Evento asignado:");

        lblNombreActividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreActividad.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreActividad.setText("Nombre de la actividad:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo:");

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(0, 0, 0));
        lblDuracion.setText("Duración:");

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFechaHora.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaHora.setText("Fecha y hora:");

        lblCapacidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCapacidad.setText("Capacidad:");

        lblLugar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLugar.setForeground(new java.awt.Color(0, 0, 0));
        lblLugar.setText("Lugar:");

        lblOrganizador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrganizador.setForeground(new java.awt.Color(0, 0, 0));
        lblOrganizador.setText("Organizador:");

        btnGestionarParticipantes.setBackground(new java.awt.Color(0, 0, 0));
        btnGestionarParticipantes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGestionarParticipantes.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarParticipantes.setText(" Gestionar Participantes");
        btnGestionarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarParticipantesActionPerformed(evt);
            }
        });

        campoEvento.setEditable(false);
        campoEvento.setBackground(new java.awt.Color(217, 217, 217));
        campoEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoEvento.setForeground(new java.awt.Color(0, 0, 0));

        campoNombre.setEditable(false);
        campoNombre.setBackground(new java.awt.Color(217, 217, 217));
        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(0, 0, 0));

        campoTipo.setEditable(false);
        campoTipo.setBackground(new java.awt.Color(217, 217, 217));
        campoTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTipo.setForeground(new java.awt.Color(0, 0, 0));

        campoDuracion.setEditable(false);
        campoDuracion.setBackground(new java.awt.Color(217, 217, 217));
        campoDuracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDuracion.setForeground(new java.awt.Color(0, 0, 0));

        campoFechaHora.setEditable(false);
        campoFechaHora.setBackground(new java.awt.Color(217, 217, 217));
        campoFechaHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoFechaHora.setForeground(new java.awt.Color(0, 0, 0));

        campoCapacidad.setEditable(false);
        campoCapacidad.setBackground(new java.awt.Color(217, 217, 217));
        campoCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoCapacidad.setForeground(new java.awt.Color(0, 0, 0));

        campoLugar.setEditable(false);
        campoLugar.setBackground(new java.awt.Color(217, 217, 217));
        campoLugar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoLugar.setForeground(new java.awt.Color(0, 0, 0));

        campoOrganizador.setEditable(false);
        campoOrganizador.setBackground(new java.awt.Color(217, 217, 217));
        campoOrganizador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoOrganizador.setForeground(new java.awt.Color(0, 0, 0));

        btnMarcarFinalizada.setBackground(new java.awt.Color(0, 0, 0));
        btnMarcarFinalizada.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMarcarFinalizada.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcarFinalizada.setText("Marcar como finalizada");
        btnMarcarFinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarFinalizadaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(237, 237, 237))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGestionarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMarcarFinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEvento)
                            .addComponent(campoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActividad)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuracion)
                    .addComponent(campoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapacidad)
                            .addComponent(campoCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLugar)
                            .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrganizador)
                            .addComponent(campoOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGestionarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMarcarFinalizada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarParticipantesActionPerformed
        ParticipantesActividadForm.actividadSeleccionada = actividadSeleccionada;
        CoordinadorAplicacion.getInstancia().mostrarParticipantesActividad();
        this.dispose();
    }//GEN-LAST:event_btnGestionarParticipantesActionPerformed

    private void btnMarcarFinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarFinalizadaActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de marcar esta actividad como finalizada?",
                "Confirmar finalización", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                CoordinadorNegocio.getInstancia().finalizarActividad(actividadSeleccionada);
                JOptionPane.showMessageDialog(this,
                        "Actividad marcada como finalizada correctamente.",
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Actualizar la vista
                btnMarcarFinalizada.setEnabled(false);
                btnMarcarFinalizada.setText("Actividad Finalizada");

                // Actualizar el objeto actividadSeleccionada para mantener consistencia
                actividadSeleccionada.setFinalizado(true);

            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error al finalizar actividad: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnMarcarFinalizadaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        volverAModuloActividades();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarParticipantes;
    private javax.swing.JButton btnMarcarFinalizada;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField campoCapacidad;
    private javax.swing.JTextField campoDuracion;
    private javax.swing.JTextField campoEvento;
    private javax.swing.JTextField campoFechaHora;
    private javax.swing.JTextField campoLugar;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoOrganizador;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblNombreActividad;
    private javax.swing.JLabel lblOrganizador;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
