/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.moduloEventos;

/**
 *
 * @author alega
 */
public class NuevoEventoForm extends javax.swing.JFrame {

    /**
     * Creates new form NuevoEventoForm
     */
    public NuevoEventoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTituloEvento = new javax.swing.JLabel();
        cbModalidades = new javax.swing.JComboBox<>();
        btnAsociarActividades = new javax.swing.JButton();
        campoTituloEvento = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        lblModalidad = new javax.swing.JLabel();
        lblOrganizador = new javax.swing.JLabel();
        campoOrganizador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaOrganizadores = new javax.swing.JList<>();
        lblFechaFin = new javax.swing.JLabel();
        dateTimePickerInicio = new com.github.lgooddatepicker.components.DateTimePicker();
        dateTimePickerFin = new com.github.lgooddatepicker.components.DateTimePicker();
        lblFechaInicio = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registrar Evento");

        lblTituloEvento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloEvento.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloEvento.setText("Ingrese el título del evento: ");

        cbModalidades.setBackground(new java.awt.Color(255, 255, 255));
        cbModalidades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbModalidades.setForeground(new java.awt.Color(0, 0, 0));
        cbModalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "En línea", "Híbrido" }));
        cbModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModalidadesActionPerformed(evt);
            }
        });

        btnAsociarActividades.setBackground(new java.awt.Color(0, 0, 0));
        btnAsociarActividades.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAsociarActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnAsociarActividades.setText("Asociar actividades");
        btnAsociarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarActividadesActionPerformed(evt);
            }
        });

        campoTituloEvento.setBackground(new java.awt.Color(255, 255, 255));
        campoTituloEvento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTituloEvento.setForeground(new java.awt.Color(0, 0, 0));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setText("Ingrese la descripción: ");

        campoDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        campoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDescripcion.setForeground(new java.awt.Color(0, 0, 0));

        lblModalidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lblModalidad.setText("Ingrese la modalidad: ");

        lblOrganizador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrganizador.setForeground(new java.awt.Color(0, 0, 0));
        lblOrganizador.setText("Seleccionar organizador:");

        campoOrganizador.setBackground(new java.awt.Color(255, 255, 255));
        campoOrganizador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoOrganizador.setForeground(new java.awt.Color(0, 0, 0));

        listaOrganizadores.setBackground(new java.awt.Color(255, 255, 255));
        listaOrganizadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaOrganizadores.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(listaOrganizadores);

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaFin.setText("Fecha fin:");

        lblFechaInicio.setText("Fecha inicio:");
        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAsociarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrganizador)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaInicio)
                                    .addComponent(dateTimePickerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaFin)
                                    .addComponent(dateTimePickerFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloEvento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloEvento)
                    .addComponent(campoTituloEvento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModalidad)
                    .addComponent(cbModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganizador)
                    .addComponent(lblFechaInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoOrganizador, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAsociarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTimePickerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTimePickerFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsociarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsociarActividadesActionPerformed

    private void cbModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModalidadesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEventoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoEventoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociarActividades;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoOrganizador;
    private javax.swing.JTextField campoTituloEvento;
    private javax.swing.JComboBox<String> cbModalidades;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePickerFin;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePickerInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblOrganizador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloEvento;
    private javax.swing.JList<String> listaOrganizadores;
    // End of variables declaration//GEN-END:variables
}
