/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author alega
 */
public class MenuPrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalForm
     */
    public MenuPrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConectaITSON = new javax.swing.JLabel();
        lblEventos = new javax.swing.JLabel();
        lblParticipantes = new javax.swing.JLabel();
        lblActividades = new javax.swing.JLabel();
        lblOrganizadores = new javax.swing.JLabel();
        btnCargaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));
        setForeground(new java.awt.Color(187, 187, 187));

        lblConectaITSON.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblConectaITSON.setForeground(new java.awt.Color(0, 0, 0));
        lblConectaITSON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConectaITSON.setText("ConectaITSON");

        lblEventos.setBackground(new java.awt.Color(255, 255, 255));
        lblEventos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEventos.setForeground(new java.awt.Color(0, 0, 0));
        lblEventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventos.setText("Eventos");
        lblEventos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblParticipantes.setBackground(new java.awt.Color(255, 255, 255));
        lblParticipantes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblParticipantes.setForeground(new java.awt.Color(0, 0, 0));
        lblParticipantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParticipantes.setText("Participantes");
        lblParticipantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblActividades.setBackground(new java.awt.Color(255, 255, 255));
        lblActividades.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblActividades.setForeground(new java.awt.Color(0, 0, 0));
        lblActividades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActividades.setText("Actividades");
        lblActividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblOrganizadores.setBackground(new java.awt.Color(255, 255, 255));
        lblOrganizadores.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblOrganizadores.setForeground(new java.awt.Color(0, 0, 0));
        lblOrganizadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrganizadores.setText("Organizadores");
        lblOrganizadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnCargaInicial.setBackground(new java.awt.Color(0, 0, 0));
        btnCargaInicial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCargaInicial.setForeground(new java.awt.Color(255, 255, 255));
        btnCargaInicial.setText("Realizar carga inicial");
        btnCargaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOrganizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(btnCargaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(lblConectaITSON, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblConectaITSON)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(btnCargaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargaInicial;
    private javax.swing.JLabel lblActividades;
    private javax.swing.JLabel lblConectaITSON;
    private javax.swing.JLabel lblEventos;
    private javax.swing.JLabel lblOrganizadores;
    private javax.swing.JLabel lblParticipantes;
    // End of variables declaration//GEN-END:variables
}
